### ISSUE TITLE
Missing fields in Order model

### ISSUE THREAD

**Issue by kamilszpila** [imsujan276/shopify_flutter#1]
Hi @imsujan276 

Thank you for your hard work on maintaining this valuable open-source project.
While using the package, I noticed that `Order` model is missing two important fields (that are used in web application): [billingAddress](https://shopify.dev/docs/api/storefront/2023-04/objects/Order#field-order-billingaddress) and [successfulFulfillments](https://shopify.dev/docs/api/storefront/2023-04/objects/Order#field-order-successfulfulfillments).

It appears that the `billingAddress` field seems to have the same type `MailingAddress` as `shippingAddress`. Considering this, I hope it will be relatively straightforward to add it.

**Comment by imsujan276** [comment]
Hi @kamilszpila , the package uses the storefront version of `2023-01` and it does not have those two fields. They are introduced in the latest version. 
but yeah, I am going to look into adding those fields

**Comment by imsujan276** [comment]
`billingAddress` and `successfulFulfillments` are now available in the `Order` model
