### ISSUE TITLE
Sign up Additional parameters

### ISSUE THREAD

**Issue by AhmedHeikal** [imsujan276/shopify_flutter#100]
SignUp with email and password, can u please add these parameters 
  'tags',   'send_email_invite', 'send_email_welcome',  'verified_email'
  
  
  And make 'phone' optional

**Comment by imsujan276** [comment]
Shopify Storefront [customerCreate](https://shopify.dev/docs/api/storefront/2024-10/mutations/customerCreate) has no any parameters that you requested:
