### ISSUE TITLE
Address not updating shopifyuser

### ISSUE THREAD

**Issue by Ratnesh-K** [imsujan276/shopify_flutter#107]
Hello @imsujan276,

Thank you for developing the package.

I am working on an E-commerce mobile application with Shopify integration.

In my application, I have an address management screen where I display all the addresses of the customer.
When I delete an address, the API responds with success, but the ShopifyUser response does not reflect the updated addresses.

Could you please help me resolve this issue?

**Comment by imsujan276** [comment]
By default, the user info is stored in the cache. 

If you need to get new data from the server, set **forceRefresh** to true


`  Future<ShopifyUser> currentUser({bool forceRefresh = false})`

**Comment by Ratnesh-K** [comment]
Thank you so much!! it worked.
