### ISSUE TITLE
Hello, I may be new to using graph ql. But, i am recieving  error when signing in a user. Can you guide me or provide some help?

### ISSUE THREAD

**Issue by Ashwin1002** [imsujan276/shopify_flutter#11]
The full stack trace error is : 
OperationException(linkException: null, graphqlErrors: [GraphQLError(message: Variable $customerAccessToken of type String! was provided invalid value, locations: [ErrorLocation(line: 1, column: 7)], path: null, extensions: {value: null, problems: [{path: [], explanation: Expected value to not be null}]})])

**Comment by imsujan276** [comment]
Can you add the code snippet?

**Comment by Ashwin1002** [comment]
I have created a signin event using bloc which is as below.
FutureOr<void> _signInUserEvent(
      SignInWithEmailPasswordEvent event, Emitter<LoginState> emit) async {
    emit(state.copyWith(loginStatus: LoginStatus.loading));
    try {
      final ShopifyUser response = await shopifyAuth.signInWithEmailAndPassword(
          email: state.email, password: state.password);

      if (response.id != null) {
        emit(state.copyWith(
          loginStatus: LoginStatus.success,
          message: 'User Logged In Successfully',
          userData: response,
        ));
      }
    } catch (e) {
      emit(state.copyWith(
        message: Errorhandler().parseErrorMessage(e),
        loginStatus: LoginStatus.failure,
      ));
    }
  }

The  above event is triggered when button pressed in sign in page. I get following error: 

 [{message: Variable $customerAccessToken of type String! was provided invalid value, locations: [{line: 1, column: 7}], extensions: {value: null, problems: [{path: [], explanation: Expected value to not be null}]}}]
[log] error => OperationException(linkException: null, graphqlErrors: [GraphQLError(message: Variable $customerAccessToken of type String! was provided invalid value, locations: [ErrorLocation(line: 1, column: 7)], path: null, extensions: {value: null, problems: [{path: [], explanation: Expected value to not be null}]})])

I have set the storefront access token and store url in the main file.

**Comment by imsujan276** [comment]
I have tested the sign-in functionality on my side and it went well. I am not able to replicate the issue you are facing.

Are you using the latest version of the plugin?
Can you double-check the Shopify credentials you have?

**Comment by imsujan276** [comment]
One of the credentials seems to be empty or null. Make sure the both email and password are present
