### ISSUE TITLE
Exception occurring when delete a user using his id 

### ISSUE THREAD

**Issue by muhammedSalihT** [imsujan276/shopify_flutter#14]
//calling function

()async{
     await ShopifyAuth.instance.deleteCustomer(
                        userId: '7459476209966',
                      );
}

// getting exception from catch

OperationException(linkException: ResponseFormatException(originalException: FormatException: Unexpected end of input (at character 1)
      
      ^
, originalStackTrace: #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501:7)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36:10)
#3      JsonDecoder.convert (dart:convert/json.dart:610:36)
#4      JsonCodec.decode (dart:convert/json.dart:216:41)
#5      HttpLink._defaultHttpResponseDecoder
link.dart:48
#6      HttpLink._parseHttpResponse
link.dart:117

is there any issue in user delete api calling? i wish to know the issue,Thanks

**Comment by imsujan276** [comment]
You are passing the wrong user ID. The user id should be something like 

> gid://shopify/Customer/123456789

So, the function should be like

``` dart
await ShopifyAuth.instance.deleteCustomer(
    userId: 'gid://shopify/Customer/123456789',
);
```
