### ISSUE TITLE
[Improvement-Request] user phone number field during creation of new customer using createUserWithEmailAndPassword method

### ISSUE THREAD

**Issue by RafatMeraz** [imsujan276/shopify_flutter#16]
When we are creating a customer with an email and password, we can send everything without a phone number. However, there is a method by which we can update the profile with a phone which is redundant work something. Is it possible to add that field during the creation of a new customer?

**Comment by imsujan276** [comment]
@RafatMeraz, Thank you for raising this update. 

Initially, adding a phone number was an issue so I removed it for the moment. Let me test it again adding it again.

**Comment by imsujan276** [comment]
The package has been updated with the improvement. You can pass phone and acceptMarketing params now but are optional. 

It is available in [v1.1.4](https://pub.dev/packages/shopify_flutter)
