### ISSUE TITLE
[Feature-Request] Wish list feature should be introduced

### ISSUE THREAD

**Issue by RafatMeraz** [imsujan276/shopify_flutter#18]
The wishlist feature is missing
- Add to wish list
- Show all wish list items
- Already added should be add to wishlist in Product(class)
- Remove from wishlist

**Comment by imsujan276** [comment]
As per my knowledge, Shopify does not provide any API to handle Wishlist/Favourites at the moment. These should be handled locally or using custom logic on our own system.

**Comment by imsujan276** [comment]
Closed because it had been idle for over a week
