### ISSUE TITLE
Query on products in specific collection

### ISSUE THREAD

**Issue by RafatMeraz** [imsujan276/shopify_flutter#21]
We have a method `getAllProductsOnQuery()` by which we can fetch products by query. Is there anything from where we can do it in specific collection of products?

**Comment by iameerhamza** [comment]
you mean this? **Future<List<Product>> getAllProductsFromCollectionById(String id)**

**Comment by RafatMeraz** [comment]
> you mean this? **Future<List> getAllProductsFromCollectionById(String id)**

no, I wanted to query/search on products of specific collections. Currently, you can search on all products, not like in a 'popular' collection.

**Comment by imsujan276** [comment]
To get or search products within collection, you can use 
`Future<List<Product>> getXProductsAfterCursorWithinCollection(String id, int limit, String startCursor, SortKeyProduct sortKey, Map<String, dynamic>? filters)`
