### ISSUE TITLE
getCollectionById throwing with Null to String type cast from ShopifyImageFromJson

### ISSUE THREAD

**Issue by reesz** [imsujan276/shopify_flutter#23]
I'm currently experiencing the following issue in `shopify_flutter: ^1.3.0`:

When trying to get a collection by it's ID, null is returned.

**Code:**
```dart
String id = "XXXX";
ShopifyStore store = ShopifyStore.instance;
Collection? collection = await store.getCollectionById("gid://shopify/Collection/$id");
```

**Log:**
```
[log] type 'Null' is not a subtype of type 'String' in type cast
```

Other collection related methods work, though:

```dart
/// Using other collection methods on the same ID works
dynamic products = await store.getAllProductsFromCollectionById("gid://shopify/Collection/$id");

/// Getting all collections works
dynamic collections = await store.getAllCollections();
```

When adding a log for the Stacktrace in the `getCollectionById`, this is the Stacktrace it prints:
```
flutter: #0      _$$_ShopifyImageFromJson (package:shopify_flutter/models/src/product/shopify_image/shopify_image.g.dart:11:40)
#1      new _$_ShopifyImage.fromJson (package:shopify_flutter/models/src/product/shopify_image/shopify_image.freezed.dart:126:7)
#2      _$ShopifyImageFromJson (package:shopify_flutter/models/src/product/shopify_image/shopify_image.freezed.dart:18:24)
#3      new ShopifyImage.fromJson (package:shopify_flutter/models/src/product/shopify_image/shopify_image.dart:17:7)
#4      Collection.fromGraphJson (package:shopify_flutter/models/src/collection/collection.dart:62:26)
#5      ShopifyStore.getCollectionById (package:shopify_flutter/shopify/src/shopify_store.dart:229:25)
<asynchronous suspension>
#6      ShopifyRepo.fetchCollection (package:oac_mobile_app/services/shopify/shopify_repo.dart:17:30)
<asynchronous suspension> 
```

Pointing to this line:
```dart
_$_ShopifyImage _$$_ShopifyImageFromJson(Map<String, dynamic> json) =>
    _$_ShopifyImage(
      originalSrc: json['originalSrc'] as String, /// <----------
      id: json['id'] as String,
      altText: json['altText'] as String?,
    );
```

It seems like the API json isn't matching the model? Which is weird, since fetching all collections seems to be no problem.

Any idea why this might be? Anything I can share to help debug this?

**Comment by reesz** [comment]
<img width="545" alt="image" src="https://github.com/imsujan276/shopify_flutter/assets/57729172/249221d9-7b1e-4ad1-8a67-a9d9e1d6b9d2">

It seems like `originalSrc` is deprecated & probably not returned by the API anymore.

**Comment by imsujan276** [comment]
which storefrontApiVersion are you using? 

not able to replicate in the default version "2023-07"

**Comment by reesz** [comment]
I use `storefrontApiVersion: '2023-07'`.

`originalSrc` is already marked as deprecated in `2023-07`:
https://shopify.dev/docs/api/storefront/2023-07/objects/image

But that's not the issue; I think I found the line that's causing the bug: `shopify_image.g.dart`
```dart
image: nodeJson['image'] != null
  ? ShopifyImage.fromJson(
    (json['node'] ?? const {})['image'] ?? const {}
  ) : null,
```

You're checking if `nodeJson['image']` is `!= null`. 
If that is the case, instead of doing `ShopifyImage.fromJson(nodeJson['image']);`, using the actual variable that was checked for; you're re-accessing the original json object with the index `'node'`.

But a couple lines earlier, you have a secondary condition which could be filling `nodeJson`:
```dart
Map<String, dynamic> nodeJson = json['node'] ?? const {};
if (json.containsKey('nodes')) {
  nodeJson = json['nodes'][0] ?? const {};
}
```

When I step through it, this if condition is triggering & the `json` I'm getting from the API call looks like:
```json
{
   "__typename":"QueryRoot",
   "nodes":[
      {
         "__typename":"Collection",
         "id":"gid://shopify/Collection/267553...",
         "handle":"sport-bras",
         "descriptionHtml":,
         "image":{
            "__typename":"Image",
            "src":"https://cdn.shopify.com/s/files/...",
            "originalSrc":"https://cdn.shopify.com/s/files/...",
            "id":"gid://shopify/CollectionImage/178695...",
            "altText":"Sport Bras"
         },
         "title":"Sport Bras",
         "updatedAt":"2023-09-04T14:25:34Z"
      }
   ]
}
```

So the thing that gets passed to the `ShopifyImage.fromJson` constructor is null, since `json['node']` is null, since it is `json['nodes'][0]`.

So this line-change should be all that's needed:
```dart
image: nodeJson['image'] != null
          ? ShopifyImage.fromJson(nodeJson['image'])
          : null,
```

**Comment by imsujan276** [comment]
Thank you. Seems like this resolves the issue.

Regarding the `Image.originalSrc` being replaced by `Image.url`, I have tested both versions, but I always get the original. SO putting it in backlog for now
