### ISSUE TITLE
Typecast error for double properties if json includes full numbers get treated as int

### ISSUE THREAD

**Issue by reesz** [imsujan276/shopify_flutter#25]
In my current scenario I am getting the JSON for the shopify product from a 3rd party service.
Could be a search provider like Algolia that stores the products json to be better searchable.
To not have duplicate models I would like to use the packages models for handling the data further in Flutter.

I am now fetching & parsing the JSON from said service & then passing it into the `Product.fromGraphJson`.
Which atm leads to a type cast error in `product_variant.dart:42`
```dart
weight: nodeJson['weight']
```

inspecting the JSON looks like this:
```json
{
  ...
  "weightUnit": "KILOGRAMS",
  "weight": 0,
  "availableForSale": true,
  ...
}
```

And it seems like the full integer `0` does not get treated as a double.
I have not had the time to debug why this isn't the case, if the same products are being fetched via the packages own client.

My current workaround is to loop through all my JSONs & convert problematic full numbers to double.
But this is quite expensive on larger amounts of products.

So maybe for double units there could be a cast like
```dart
weight: (nodeJson['weight'] as num).toDouble()
```

If `weight` isn't something that can be cast to double it will throw an error, but that is already the case right now if it's anything else than a double.
This would allow for safer `fromJson` construction.

**Comment by imsujan276** [comment]
Thank you. 

updated it as 

``` dart
weight: double.tryParse(nodeJson['weight'].toString()) ?? 0.0
```
