### ISSUE TITLE
[Improvement] Include selectedOptions on ProductVariantCheckout in Order

### ISSUE THREAD

**Issue by reesz** [imsujan276/shopify_flutter#26]
When fetching a Product the attached variants are handled with the class `ProductVariant`.

When fetching Orders (customQuery + using the `getAllOrdersQuery` from the plugin):
```dart
Map<String, dynamic>? res = await ShopifyCustom.instance.customQuery(
  gqlQuery: getAllOrdersQuery,
  variables: {
    'accessToken': customerAccessToken,
    'sortKey': sortKey.parseToString(),
    'reverse': false,
  },
);

if (res == null) {
 return;
}

final orderResult = (res['customer']['orders'] ?? {}) as Map<String, dynamic>;

Orders orders = Orders.fromGraphJson(orderResult);
```

The `Orders` which get parsed use `ProductVariantCheckout` to handle variant on the `LineItemOrder`.
Both variant classes mostly hold the same properties, but `ProductVariantCheckout` misses the crucial property `selectedOptions`, which can be key in displaying the purchased options in the order.

[From what I can see in the docs](https://shopify.dev/docs/api/storefront/2023-07/objects/OrderLineItem) the resource `OrderLineItem` references the same `ProductVariant` resource on the API as the product.

I'd suggest to include `selectedOptions` into the `ProductVariantCheckout` class/query.

**Comment by imsujan276** [comment]
`selectedOptions` is now available in `ProductVariant `
