### ISSUE TITLE
[Improvement] getAllOrdersQuery is missing product fields for lineItem variants

### ISSUE THREAD

**Issue by reesz** [imsujan276/shopify_flutter#27]
When using the `getAllOrdersQuery` query from the plugin to fetch a customers orders, the returned `ProductVariantCheckout` on an `Order`'s `LineItemOrder` doesn't include the related parent product.

Having access to the parent product can be useful when trying to link the customer back to the product page, from viewing an order.

For consistency I'd suggest adding the `product` fields into the `getAllOrdersQuery`, so the parent product on the Order's lineItems is available.

**Comment by imsujan276** [comment]
The product ID is available now in `LineItemOrder`

you can access it as 

``` dart
    for(var order in orders) {
        for(var item in order.lineItems.lineItemOrderList){
          print("${item.title} | ${item.productId}");
        }
      }
```
