### ISSUE TITLE
How to upload images or files

### ISSUE THREAD

**Issue by iameerhamza** [imsujan276/shopify_flutter#28]
im creating a page where user can attach some images with the returnable items , so i want to know that how to upload the images in shopify using graphql api

**Comment by imsujan276** [comment]
can you provide more info? 

currently, the package does not support image upload. But you can use custom query to upload product images using the admin API. **[MORE INFO](https://shopify.dev/docs/api/admin-rest/2023-10/resources/product-image)**

**Comment by imsujan276** [comment]
As per Shopify doc, the `originalSource` is `an external URL (for images only) or a [staged upload URL](https://shopify.dev/api/admin-graphql/latest/mutations/stageduploadscreate).`

That means it only accepts the URL to the image. For this, you need to upload the image in temporary image server first, get the URL, and uset that URL in the `originalSource` field. 

Once done, you can delete the image in the temporary server.
