### ISSUE TITLE
[Bug] getCheckoutInfoQuery error when converting into the Checkout model. 

### ISSUE THREAD

**Issue by jschaeken** [imsujan276/shopify_flutter#29]
When a checkout info query is made on a completed order, the Gql returns an 'Order' typename within the Checkout typename like below. (I obscured the key)

order: {__typename: Order, id: gid://shopify/Order/5848740561236?key=20397cf872......e1075132807}

This is causing the Checkout.fromJson to throw an error, which I stacked traced below:

stackTrace: #0      _$$_OrderFromJson
order.g.dart:11
#1      new _$_Order.fromJson
order.freezed.dart:481
#2      _$OrderFromJson
order.freezed.dart:18
#3      new Order.fromJson
order.dart:68
#4      _$$_CheckoutFromJson
checkout.g.dart:33
#5      new _$_Checkout.fromJson
checkout.freezed.dart:515
#6      _$CheckoutFromJson
checkout.freezed.dart:18
#7      new Checkout.fromJson
checkout.dart:48
#8      ShopifyCheckout.getCheckoutInfoQuery
shopify_checkout.dart:77
  

I believe it is looking for a full Order object, whereas the Gql document returns just the id within the Order typename.

**Comment by imsujan276** [comment]
Are you using your own custom gql?

if not, `getCheckoutInfoQuery` result always contains the Order object or null.

**Comment by imsujan276** [comment]
Closing the issue since there is no update from @jschaeken
