### ISSUE TITLE
Social Authentications

### ISSUE THREAD

**Issue by abubakarflutter** [imsujan276/shopify_flutter#32]
I want to integrate social media authentication in to my app. How can i do it? 
It may be already implemented in the package but i don't know. If it is then guide me how can i, if its not then how can i do this?

**Comment by imsujan276** [comment]
Social Login is not supported by Shopify Graphql yet. So, if you want to add the feature, you need to handle it yourself

**Comment by imsujan276** [comment]
Closing the issue since there is no update from @abubakarflutter

**Comment by asadamatic** [comment]
@imsujan276 From Shopify Docs

> As of January 2024, the [Customer Account API](https://shopify.dev/docs/api/customer) is generally available. It's now the recommended cross-platform method for managing customer data. Learn more about [getting started with the Customer Account API](https://shopify.dev/docs/custom-storefronts/building-with-the-customer-account-api).
