### ISSUE TITLE
how to add billing address upon checkout

### ISSUE THREAD

**Issue by peteroleeman** [imsujan276/shopify_flutter#33]
hi, need help. How to add billing address upon checkout

**Comment by imsujan276** [comment]
Hello @peteroleeman 

As of today, [Shopify GraphQL](https://shopify.dev/docs/api/storefront/2024-01/mutations/checkoutCreate) only accepts the **shippingAddress** while checking out.  

So, if your store needs the billing address too, you can make them required in the CheckoutPage of the Shopify itself.

**Comment by peteroleeman** [comment]
i see, thank you    在 2024年1月9日 星期二 下午03:11:58 [GMT+8]， Sujan ***@***.***> 寫道：  
 
 


Hello @peteroleeman

As of today, Shopify GraphQL only accepts the shippingAddress while checking out.

So, if your store needs the billing address too, you can make them required in the CheckoutPage of the Shopify itself.
