### ISSUE TITLE
1.5.3 - Errors

### ISSUE THREAD

**Issue by vptcnt** [imsujan276/shopify_flutter#34]
Hello,

In the version 1.5.3, there are some errors

File : /lib/graphql_operations/storefront/mutations/customer_default_address_update.dart
- Missing ":" after $customerAccessToken

File : /lib/graphql_operations/storefront/queries/get_all_pages.dart
File : /lib/graphql_operations/storefront/queries/get_page_by_handle.dart
- url must be onlineStoreUrl

File : /lib/shopify/shopify.dart
- Missing some exports :
        export 'src/shopify_custom.dart';
        export 'src/shopify_page.dart';
        export 'src/shopify_store.dart';

File : /lib/shopify/src/shopify_auth.dart
- Function createUserWithEmailAndPassword
       *  firstName and lastName can be String? as they are not necessary
       * Variables :  'phone': phone (instead 'phone': phone ?? '' ) is enough as the phone is not mandatory

**Comment by imsujan276** [comment]
Thank you @vptcnt for pointing out these issues. 

They have been resolved in version 1.5.4
