### ISSUE TITLE
After adding a new address its not showing in the list until i do restart my app

### ISSUE THREAD

**Issue by GeekstackDevelopers** [imsujan276/shopify_flutter#38]
final accessToken = await shopifyAuth.currentCustomerAccessToken;
      final currentUser = await shopifyAuth.currentUser();

      **log(currentUser?.address?.addressList.length.toString() ?? 'null');**

      await shopifyCustomer.customerAddressCreate(
          firstName: addressModel.firstName,
          lastName: addressModel.lastName,
          phone: addressModel.mobileNumber,
          address1: addressModel.addressLine1,
          address2: addressModel.addressLine2,
          company: addressModel.companyName,
          city: addressModel.town,
          zip: addressModel.postalCode,
          country: 'India',
          customerAccessToken: accessToken);

      **log(currentUser?.address?.addressList.length.toString() ?? 'null');**

both before and after adding a new address im getting the same length of list
i felt the same on update user details

**Comment by asadamatic** [comment]
@GeekstackDevelopers Are you refreshing the data and UI on the update of the address and user details?

**Comment by GeekstackDevelopers** [comment]
@asadamatic i am printing the length of the list using log() before creating an address and after its done.. in both its printing the same count. that means its not updating instantly.

**Comment by asadamatic** [comment]
@GeekstackDevelopers You have to reload the addresses and the user's profile.

**Comment by imsujan276** [comment]
@GeekstackDevelopers are you still facing this issue?
