### ISSUE TITLE
Checkout Object Should have Discount Related Data

### ISSUE THREAD

**Issue by asadamatic** [imsujan276/shopify_flutter#44]
### Shopify Checkout object
Checkout object can have these useful properties to help display discount informations to customers at checkout.

```json 
{
  "applied_gift_cards": [],
  "attributes": {},
  "billing_address": {},
  "buyer_accepts_marketing": false,
  "cart_level_discount_applications": [],
  "currency": "CAD",
  "customer": {},

  // Discount Related Properties
  "discount_applications": [],
  "discounts_amount": 4224,
  "discounts_savings": -4224,

  "email": "cornelius.potionmaker@gmail.com",
  "gift_cards_amount": 0,
  "id": 29944051400769,
  "line_items": [],
  "line_items_subtotal_price": 42249,
  "name": "#29944051400769",
  "note": null,
  "order": null,
  "order_id": null,
  "order_name": "#29944051400769",
  "order_number": "#29944051400769",
  "requires_shipping": true,
  "shipping_address": {},
  "shipping_method": {},
  "shipping_price": 0,
  "tax_lines": [],
  "tax_price": 0,
  "total_price": 38025,
  "transactions": []
}
```

**Comment by imsujan276** [comment]
Hello @asadamatic, this would be useful for the customers to show the discount information 

but the [Checkout](https://shopify.dev/docs/api/storefront/2024-01/objects/checkout) object has no any attributes like `discounts_amount` and `discounts_savings`

Can you fill me up with more info from where I could get those data?

**Comment by asadamatic** [comment]
@imsujan276 I'm referring to this [documentation](https://shopify.dev/docs/api/liquid/objects/checkout), but I found out that it is deprecated.

**Comment by imsujan276** [comment]
That documentation is for the `Liquid` API, which differs from the `Storefront API`.
