### ISSUE TITLE
Checkout Flow

### ISSUE THREAD

**Issue by abubakarflutter** [imsujan276/shopify_flutter#46]
HI Sujan, hope you're good. 
Please note its not an actual issue in the package, rather I want to clear the checkout flow as I'm bit confused. 

So, now I am on the Cart Screen where all of my items in the checkout object are listed and clicking on the "Checkout" button is normally opening the web page (as I am passing the webURL to the webview) , but I want to use the following API  "checkoutCompleteWithTokenizedPaymentV3" , from where I will get the "token" which is being used as  'paymentData': token 
moreover this API is returning the payment > id ,   how this is useful to complete the checkout ? as I just have to pass the payment Type like APPLE_PAY,  or should i have to integrate the APPLE_PAY natively in my app to process the payment and then run this API ? 

Would you please clear me the flow, when this API will be called ? and after this how the payment will be processed actually by using this API ? 

And do you know about the Shopify Payments? What if i enable that in my store and how that will work? Would I have to open the webview with that as well or not?

Thank you, Sujan for making this great package for us, and I'm waiting for your reply on the above query.

**Comment by imsujan276** [comment]
Thank you for raising this question.

1. "paymentType" indicates the type of third-party payment method used.
2. "token" is the identifier that the payment provider generates that you need to add natively in the app to capture the payment.
3. I have not much info about the "Shopify Payments"

I have updated the package to **v1.5.10**. Now, the `checkoutCompleteWithTokenizedPaymentV3` will return `TokanizedCheckout` model. So, once you get the data, you have to open the webview for the `TokanizedCheckout.nextActionUrl` which will lead the user to complete the 3D Secure payment flow
