### ISSUE TITLE
Shipping Method

### ISSUE THREAD

**Issue by MoeezChohan1089** [imsujan276/shopify_flutter#47]
Hy sir,
I hope you are doing well, i just want to inform you that you should implement also shipping method API (object, mutations and queries). sometimes user can change shipping method so i want to add shipping method 
please add it also in your code
Thanks for your cooperation

**Comment by asadamatic** [comment]
@MoeezChohan1089 Shipping methods are available in the `Checkout` object as `availableShippingRates`. If you have set `shippingAddress` for a checkout using `shippingAddressUpdate`, you'll get a list of `ShippingRates` ( Shipping Method ) in `availableShippingRates`.

> The provided shipping address region must be supported by the store.

**Comment by MoeezChohan1089** [comment]
ok thanks for it

**Comment by MoeezChohan1089** [comment]
sir i checked it i added custom shipping method and also region defined then still not showing availableshipping rates but i checked in shoppify webview here its showing shipping method which i selected now tell me how i can show shipping method in app section

**Comment by imsujan276** [comment]
Can you provide the minimal code showing what you are doing to achieve it?

**Comment by MoeezChohan1089** [comment]
Ok sir I will send you a code and also screenshot I think you will better understand with reference of screenshot

**Comment by MoeezChohan1089** [comment]
![Screenshot_20240313-094516](https://github.com/imsujan276/shopify_flutter/assets/87126520/33c2be62-1310-4250-a772-9a450c2118a0)
![Screenshot_20240313-094519](https://github.com/imsujan276/shopify_flutter/assets/87126520/896769f0-99f1-45d2-a897-3f71681817e8)

here you can check i am getting this shipping method when i will checkout then should be change shipping method but its not showing data this is the dummy data which you can see in these screenshoots. so according to your talk i used availableshippingrates but its showing null list so please tell me how i can get me shipping rates

**Comment by MoeezChohan1089** [comment]
if you say that we should update shippingaddress first then will show shippingrates then i am updating shippingaddress (address, full name, phone number, country, city, postal code) after add shipping fields then still showing null availableshippingrates

**Comment by imsujan276** [comment]
It would really be helpful if you could provide me with the minimal reproducible code.

It is difficult to understand the cause from the UI only

**Comment by imsujan276** [comment]
It was closed because the issue had been idle for over a week.
