### ISSUE TITLE
Checkout Details are not Localised.

### ISSUE THREAD

**Issue by asadamatic** [imsujan276/shopify_flutter#48]
The checkout info fetched using `getCheckoutInfoQuery`, does not have localized content as provided in the `setConfig` method.
All of the other APIs that I have used, seem to be working correctly for the localized content.

<img src="https://github.com/imsujan276/shopify_flutter/assets/37589169/d088249d-9d59-456b-b358-8189f882e06b" alt="product_localised" width="300"/>
<img src="https://github.com/imsujan276/shopify_flutter/assets/37589169/1c856064-c905-42f2-af58-41b7a5c1b45a" alt="cart_not_localised" width="300"/>

**Comment by imsujan276** [comment]
Hi @asadamatic Thank you for finding this issue. 

I have tried it myself and haven't been able to replicate this on my side. It worked.

So, can you provide me with more info on how you set it up and a minimal reproducible code?

**Comment by asadamatic** [comment]
- Config

```dart
 ShopifyConfig.setConfig(
              storefrontAccessToken: storeFrontAccessTokenModest,
              storeUrl: storeUrlTryModest,
              adminAccessToken: adminAccessTokenModest,
              cachePolicy: CachePolicy.networkOnly,
              language: controller.locale.languageCode,
            );
```

- Fetching Checkout

```dart
  await _shopifyCheckout
        .getCheckoutInfoQuery(getShippingInfo: false)
        .then((value) {
      checkout = value;
     ...
    });

> All the other APIs are working fine with localisation except `getCheckoutInfoQuery` and `getAllOrders`.

**Comment by imsujan276** [comment]
To display the localized product from the checkout lineitems, you should access the variant product of the lineitem.

Example

```dart
final lineItems = checkout.lineItems;
final firstLiteItem = lineItems.first;
print("Localized name: ${firstLiteItem.variant?.product?.title}");

```
