### ISSUE TITLE
Support for Currencies Depending on the Country Code.

### ISSUE THREAD

**Issue by asadamatic** [imsujan276/shopify_flutter#49]
I couldn't find a way in the SDK to get prices according to user's locale.

I tried `ShopifyCustom` to make a query  on products with `inContext` ([Reference](https://shopify.dev/docs/custom-storefronts/building-with-the-storefront-api/markets/international-pricing)), but it didn't return the currency code for the provided country code.

My query
```gql
query alProducts @inContext(country: PK) {  
  products(first: 5) {
    pageInfo {
      hasNextPage
    }
    edges {
      cursor
      node {
        options(first: 50) {
          id
          name
          values
        }
        variants(first: 250) {
          edges {
            node {
              id
              title
              image {
                altText
                id
                originalSrc
              }
              priceV2 {
                amount
                currencyCode
              }
              compareAtPriceV2 {
                amount
                currencyCode
              }
              weight
              weightUnit
              availableForSale
              sku
              requiresShipping
              quantityAvailable
              selectedOptions {
                name
                value
              }
            }
          }
          pageInfo {
            hasNextPage
          }
        }
        availableForSale
        collections(first: 250) {
          edges {
            node {
              description
              descriptionHtml
              id
              handle
              updatedAt
              title
            }
          }
        }
        createdAt
        description
        descriptionHtml
        handle
        id
        onlineStoreUrl
        productType
        publishedAt
        tags
        title
        updatedAt
        vendor
        images(first: 250) {
          edges {
            node {
              altText
              id
              originalSrc
            }
          }
        }
      }
    }
  }
}
```

**Comment by imsujan276** [comment]
The code snippet you provided did not return the price on my side. I had to update `priceV2` to `price`.

While testing, it did not return the localized price for the country 'PK' only. I tried it with `CA`, `US`, `NP` and `ES`, it worked everytime.

**Country as 'ES'**

<img width="1001" alt="Screenshot 2024-03-18 at 1 13 19 PM" src="https://github.com/imsujan276/shopify_flutter/assets/11173809/86453621-8b81-4c55-844c-de5b4087a295">

**Country as 'CA'**

<img width="716" alt="Screenshot 2024-03-18 at 1 15 02 PM" src="https://github.com/imsujan276/shopify_flutter/assets/11173809/108b76a6-7f16-4fd9-bf03-ab6401f7b354">

**Country as 'PK'**

<img width="678" alt="Screenshot 2024-03-18 at 1 15 54 PM" src="https://github.com/imsujan276/shopify_flutter/assets/11173809/c4881b57-4c12-434d-b4a0-3cf3e2561819">

I can't actually figure out why this is happening. I guess It is coming from the Shopify store config

**Comment by asadamatic** [comment]
@imsujan276 Thanks a lot. I will check the store config.
Is there a plan to support multiple currencies within the SDK?

**Comment by imsujan276** [comment]
I am not thinking of adding this feature as I am occupied with work. 

But PR is welcome

**Comment by asadamatic** [comment]
@imsujan276 It was a problem with the store configuration.
