### ISSUE TITLE
Update Add to Cart

### ISSUE THREAD

**Issue by MoeezChohan1089** [imsujan276/shopify_flutter#5]
Hy sir,
Hope you are doing well. sir i am using this function for update add to cart but its creating issue. Please confirm it that is it true 

updateProductQuantity({required LineItem lineItem}) async {
    try {
      final currentCheckOutId = await getCheckOutId();
      final response = await shopifyCheckout.updateLineItemsInCheckout(
        checkoutId: currentCheckOutId,
        lineItems: [
          lineItem,
        ],
      );
      currentCart = response;
      update();
      log("====> SUCCESS product update in cart $response  <=====");
    } catch (e) {
      log("====> ERROR product update in cart $e <=====");
    }
  }
  
  showing error: ERROR product update in cart OperationException(linkException: null, graphqlErrors: [GraphQLError(message: Type mismatch on variable $lineItems and argument lineItems ([CheckoutLineItemInput!]! / [CheckoutLineItemUpdateInput!]!), locations: [ErrorLocation(line: 3, column: 27)], path: [mutation checkoutLineItemsUpdate, checkoutLineItemsUpdate, lineItems], extensions: {code: variableMismatch, variableName: lineItems, typeName: [CheckoutLineItemInput!]!, argumentName: lineItems, errorMessage: Type mismatch})]) 
  
  please solve it asap

**Comment by imsujan276** [comment]
THe issue has been fixed and published in **v1.0.9**
