### ISSUE TITLE
Calling currentUser() after creating new account returns null

### ISSUE THREAD

**Issue by kamilszpila** [imsujan276/shopify_flutter#50]
Calling `currentUser()` after creating new account returns null instead of returning valid `ShopifyUser` object
```dart
    await ShopifyAuth.instance
        .createUserWithEmailAndPassword(email: email, password: password);

    final user = await ShopifyAuth.instance.currentUser(); // user is null
```

**Comment by imsujan276** [comment]
You have to login in order to get the current user.

**Comment by kamilszpila** [comment]
Why does it work this way?
Cannot we update shopify user after sign up like this? https://github.com/imsujan276/shopify_flutter/pull/51

**Comment by imsujan276** [comment]
Yeah, we can. I must have missed it in the signup function. Thanks for pointing it out
