### ISSUE TITLE
How to fetch all cart item ?

### ISSUE THREAD

**Issue by fathomkiran** [imsujan276/shopify_flutter#52]
can you please let us know how to fetch all cart items?

**Comment by imsujan276** [comment]
The cart items are associated with the `Checkout` object. 
So, you can get the checkout data from the checkout ID using this function.
```dart
 Future<Checkout> getCheckoutInfoQuery({String checkoutId})
``` 
and access the cart items as 
```dart
final cartIitems = checkout.lineItems;
```

**Comment by fathomkiran** [comment]
how to manage a cart before checkout?

**Comment by imsujan276** [comment]
Please go through the [documentation](https://github.com/imsujan276/shopify_flutter?tab=readme-ov-file#shopify-checkout). It has the `ShopifyCheckout` object responsible for all the checkout functionality.
