### ISSUE TITLE
How to fetch the checkout orders ?

### ISSUE THREAD

**Issue by fathomkiran** [imsujan276/shopify_flutter#53]
option 1: 
I am getting 404 for the below API.

```
  Future<void> fetchOrders(String customerAccessToken) async {
    const String apiUrl = 'https://myshopify.com/orders.json';
    try {
      final response = await http.get(
        Uri.parse(apiUrl),
        headers: {
          'Content-Type': 'application/json',
          'X-Shopify-Storefront-Access-Token': customerAccessToken,
        },
      );

      if (response.statusCode == 200) {
        final Map<String, dynamic> responseData = json.decode(response.body);
        print('responseData: $responseData');
        final List<dynamic> orders = responseData['orders'];
        print('orders: $orders');
      }
      print('responseData: statusCode: ${response.statusCode}');
    } catch (e) {
      print('e: $e');
    }
  }
```

option 2: 

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'String' in type cast
#0      _$$ShippingAddressImplFromJson (package:shopify_flutter/models/src/order/shipping_address/shipping_address.g.dart:13:36)
#1      new _$ShippingAddressImpl.fromJson (package:shopify_flutter/models/src/order/shipping_address/shipping_address.freezed.dart:316:7)
#2      _$ShippingAddressFromJson (package:shopify_flutter/models/src/order/shipping_address/shipping_address.freezed.dart:18:27)
#3      new ShippingAddress.fromJson (package:shopify_flutter/models/src/order/shipping_address/shipping_address.dart:28:7)
#4      Order.fromGraphJson (package:shopify_flutter/models/src/order/order.dart:53:27)
#5      Orders._getOrderList.<anonymous closure> (package:shopify_flutter/models/src/order/orders/orders.dart:26:47)
#6      List.forEach (dart:core-patch/growable_array.dart:416:8)
#7      Orders._getOrderList (package:shopify_flutter/models/src/order/orders/orders.dart:26:12)
#8      Orders.fromGraphJson (package:shopify_flutter/models/src/order/orders/orders.dart:17:18)
#9      ShopifyCheckout.getAllOrders (package:shopify_flutter/shopify/src/shopify_checkout.dart:146:28)
<asynchronous suspension>
#10     _ShopifyOrderScreenState.getOrders (package:flashwave/screens/shopify/shopify_order_screen.dart:58:23)
<asynchronous suspension>

```
  getOrders() async {
    if (isLoggedIn) {
      final accessToken = await ShopifyAuth.instance.currentCustomerAccessToken;
      final allOrders = await ShopifyCheckout.instance.getAllOrders(
        accessToken!,
      );
      print('allOrders: $allOrders');
      setState(() {
        orders = allOrders ?? [];
      });
    }
  }
```

**Comment by imsujan276** [comment]
Hi @fathomkiran 

For option 1:
The URL should be `https://SHOP.myshopify.com/admin/orders.json?status=any&fulfillment_status=any `

For Option 2: 
I tried to replicate this in the example app but it ran OK, without any issues.

**Comment by imsujan276** [comment]
Closing the issue as there is no update for more than a week
