### ISSUE TITLE
Media & Video Object in Product 

### ISSUE THREAD

**Issue by abubakarflutter** [imsujan276/shopify_flutter#59]
Hi, 

I just uploaded/added video in my product on Shopify dashboard - but I am unable to get that in Product model/object.  product query is not containing that node Media , as far i have checked. 
Would you please add that in Product, as my requirement is to show the video on the Product Detail Page. 

Thank you

[https://shopify.dev/docs/api/admin-graphql/2024-01/interfaces/Media](https://shopify.dev/docs/api/admin-graphql/2024-01/interfaces/Media)

**Comment by imsujan276** [comment]
Hi @abubakarflutter 

media list is added to product in latest version of the package `1.5.18`
