### ISSUE TITLE
Access token renewal must happen before a token expires

### ISSUE THREAD

**Issue by adarshwebcastle** [imsujan276/shopify_flutter#60]
In sample code, if **isTokenExpired** then you are calling **renewCurrentAccessToken**, 

 ```
Future<void> _checkIfLoggedIn() async {
    try {
      final isTokenExpired = await shopifyAuth.isAccessTokenExpired;
      log('isTokenExpired: $isTokenExpired');
      if (isTokenExpired) {
        setState(() => shopifyUser = null);
        final accessToken = await shopifyAuth.currentCustomerAccessToken;
        if (accessToken != null) {
          await shopifyAuth.renewCurrentAccessToken(accessToken);
          final user = await shopifyAuth.currentUser();
          log('user after token refresh: $user');
          setState(() => shopifyUser = user);
        }
      } else {
        final user = await shopifyAuth.currentUser();
        setState(() => shopifyUser = user);
      }
      log(shopifyUser.toString());
    } catch (e) {
      debugPrint(e.toString());
    }
  }
```

In [documentation](https://shopify.dev/docs/api/storefront/2024-01/mutations/customerAccessTokenRenew) it's showing that **Access token renewal must happen before a token expires. If a token has already expired, a new one should be created instead via customerAccessTokenCreate.**. 

Can you rewrite the sample code accordingly if the doc is correct.

**Comment by imsujan276** [comment]
Hi @adarshwebcastle 

auto-renewal of the access token has been handled while getting the access token. I have also updated the example file.
