### ISSUE TITLE
Error on this method getProductsByIds

### ISSUE THREAD

**Issue by Valerio-Di-Stefano** [imsujan276/shopify_flutter#61]
When a Product no longer exists it does not return the other products in the getProductsByIds method

**Error:**

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: OperationException(linkException: null, graphqlErrors: [GraphQLError(message: Variable $ids of type [ID!]! was provided invalid value for 4 (Invalid global id `Product id doesn't exist`), locations: [ErrorLocation(line: 1, column: 7)], path: null, extensions: {value: [gid://shopify/Product/9253140693317, gid://shopify/Product/9253140463941, gid://shopify/Product/9253140693317, gid://shopify/Product/9253139939653, Product id doesn't exist], problems: [{path: [4], explanation: Invalid global id `Product id doesn't exist`, message: Invalid global id `Product id doesn't exist`}]})])
#0      ShopifyError.checkForError (package:shopify_flutter/mixins/src/shopify_error.dart:7:35)
#1      ShopifyStore.getProductsByIds (package:shopify_flutter/shopify/src/shopify_store.dart:110:5)
<asynchronous suspension>
#2      _CartScreenState.initState.<anonymous closure>.<anonymous closure> (package:babyshop/screens/cart/cartscreen.dart:40:42)

<asynchronous suspension>

**Comment by imsujan276** [comment]
This is something the Shopify Storefront handles itself and throws error if the ID is invalid.
