### ISSUE TITLE
Can add the shopping cart module function?

### ISSUE THREAD

**Issue by WangXiaoRi** [imsujan276/shopify_flutter#65]
Add the shopping cart module function to get the detailed discount information for each item in the shopping cart list after the discount is applied. Instead of using the checkout module directly, I had to rewrite the shopping cart interface logic to get the discount information.

**Comment by imsujan276** [comment]
I have no plan to add the new feature as I am already fully occupied.

You are free to create a PR

**Comment by cc-bilal** [comment]
Did you add the CART?

**Comment by WangXiaoRi** [comment]
> Did you add the CART?

The framework uses checkout as its cart. So I can use Add to checkout as add shopping cart.

**Comment by imsujan276** [comment]
The Cart module has been added. Please check v2.1.0

**Comment by WangXiaoRi** [comment]
grateful



发自我的iPhone


------------------ Original ------------------
From: Sujan Gainju ***@***.***&gt;
Date: Sat,Sep 7,2024 3:05 PM
To: imsujan276/shopify_flutter ***@***.***&gt;
Cc: WangXiaoRi ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [imsujan276/shopify_flutter] Can add the shopping cart modulefunction? (Issue #65)





 
Closed #65 as completed.
