### ISSUE TITLE
Null Exception When Checkout has Expired.

### ISSUE THREAD

**Issue by asadamatic** [imsujan276/shopify_flutter#68]
The method `getCheckoutInfoQuery` results in `Null Exception` being thrown, when the checkout, corresponding to the provided `checkout_id` has expired.

```
/// Null exception is thrown here
Checkout.fromJson(_queryResult.data!['node'])
```

I have handled it, by saving the `createdDate` and `updatedDate` locally, and using this rule from the community discussions to determine if the checkout has expired.

> Checkouts three months old or more that haven’t been updated in over a month, don’t have transactions, don’t come from draft orders, and have no orders are eligible for deletion in clean up jobs. [Link](https://community.shopify.com/c/hydrogen-headless-and-storefront/checkout-object-lifetime/m-p/826130/highlight/true#M529)

I'm wondering if it would be a good idea to handle this in the SDK itself.

**Comment by imsujan276** [comment]
The package is not storing the checkout_id in it. so it has no idea how old the checkout id is.  So, it is best to handle it by the app itself

**Comment by asadamatic** [comment]
My implementation, in case if anyone needs it.

```
bool get _isCheckoutValid {
    final now = DateTime.now().toUtc();

    if (_checkoutCreatedDate == null || _checkoutUpdatedDate == null) {
      return false;
    }
    final isThreeMonthsOld = now.difference(_checkoutCreatedDate!).inDays >= 90;
    final isUpdatedInOverAMonth =
        now.difference(_checkoutUpdatedDate!).inDays >= 30;
    // If the checkout is created less than 90 days ago, return true
    if (!isThreeMonthsOld) {
      return true;
    }
    return isThreeMonthsOld && isUpdatedInOverAMonth;
  }
  ```
