### ISSUE TITLE
Missing fields on getAllProducts function.

### ISSUE THREAD

**Issue by kdokhanx98** [imsujan276/shopify_flutter#7]
Hi There,

Thank you for your supporting this package.
I am trying to use 'getAllProducts' function but I keep getting this error, Are you already aware of this and working on a fix?
Thanks in advance.

<img width="954" alt="Screenshot 2023-08-29 at 3 51 28 PM" src="https://github.com/imsujan276/shopify_flutter/assets/76620656/6ff3b222-9a3e-492b-9714-57a9adf652c9">

**Comment by imsujan276** [comment]
Thank you for raising the issue. This issue has been fixed in v1.0.13.
