### ISSUE TITLE
product details metafild or metafieldDefinitions       metafield(namespace: "namespace", key: "namespace")

### ISSUE THREAD

**Issue by ramniwas08** [imsujan276/shopify_flutter#70]
product details metafild or metafieldDefinitions       metafield(namespace: "namespace", key: "namespace") not working

**Comment by imsujan276** [comment]
Can you provide more info and minimum reproducible code for the issue you are getting?

**Comment by ramniwas08** [comment]
please tel mai how to filter product by multiple tags and price

*Ramniwas Saharan*
Flutter Devloper | www.devsmartstore.in

M: +91 7424891134

E: ***@***.***

A: Dev Smart Store, Street, City, Churu Rural, Rajasthan 331001 India

[image: instagram icon] <https://www.instagram.com/ramniwas08/>

**Comment by imsujan276** [comment]
You can use ShopifyStore insatnce filter the products like 

 filters available queries

>   Future<List<Product>> getXProductsAfterCursorWithinCollection(String id, int limit, String startCursor, SortKeyProduct sortKey, Map<String, dynamic>? filters)
>   Future<List<Product>?> searchProducts(String query, {int limit = 15, String? startCursor, SearchSortKeys sortKey = SearchSortKeys.RELEVANCE, bool reverse = false, Map<String, dynamic>? filters})



Please find the details in **[Product Filters](https://github.com/imsujan276/shopify_flutter?tab=readme-ov-file#filter-products)** section
