### ISSUE TITLE
Customer Auth Using “New Customer Accounts” 

### ISSUE THREAD

**Issue by deliciousMuffin78** [imsujan276/shopify_flutter#73]
Many shops switched to passwordless shopify logins so would be useful to allow login using new oauth 2.0 flow where customer enters email > receive 6 digit code by text/email from shopify to complete login. Extra plus if this can also return Shopify’s customer global id to simplify other in-app functions.

**Comment by imsujan276** [comment]
Shopify storefront has not provided the feature to graphql yet

you can see all the available customer-related operations [HERE](https://shopify.dev/docs/api/storefront/2024-07/mutations/customerAccessTokenCreate)
