### ISSUE TITLE
Changing API version giving error

### ISSUE THREAD

**Issue by MoeezChohan1089** [imsujan276/shopify_flutter#76]
I just got warning from shopify to use the latest API versions which is the 2024-07 , So i just changed the API version but some of the APIs are not working, like addLineItemToCart  giving me this error 
```message: Field 'checkoutCreate' doesn't exist on type 'Mutation'```

there are some more APIs which are giving error with this API version, would you please check and update it,  Thank you

**Comment by imsujan276** [comment]
It seems Shopify has depreciated the **checkout" module entirely from v2024-07. We need to use **Cart** in place of that. 

I will be working on it

**Comment by imsujan276** [comment]
[shopify_flutter v2.0.0](https://pub.dev/packages/shopify_flutter/versions/2.0.0) is released. 

Changelog:

- Depreciated ShopifyCheckout from Shopify API version 2024-07
- Introduced ShopifyCart to perform cart operation
- Introduced ShopifyOrder to access customer orders
