### ISSUE TITLE
Customer Login Issue 

### ISSUE THREAD

**Issue by Sp2021bca** [imsujan276/shopify_flutter#77]
While Loggin with Email and password Api Version 2024-07.

OperationException(linkException: null, graphqlErrors: [GraphQLError(message: Field 'lastIncompleteCheckout' doesn't exist on type 'Customer', locations: [ErrorLocation(line: 58, column: 5)], path: [query, customer, lastIncompleteCheckout], extensions: {code: undefinedField, typeName: Customer, fieldName: lastIncompleteCheckout})])

**Comment by imsujan276** [comment]
**lastIncompleteCheckout** is depreciated in the latest Flutter version 2024-07.

This has been fixed in the latest version [2.1.0](https://pub.dev/packages/shopify_flutter/versions/2.1.0).
