### ISSUE TITLE
cart api return Title  : Default Title insted of main title

### ISSUE THREAD

**Issue by Sp2021bca** [imsujan276/shopify_flutter#78]
Cart Api returns Default Title but checkout api returning correct title from main product title. also user address not getting reflected in user we need to open app again to see the changes provide re-init options for Current user instance , Aslo when we update address updated in cart not reflecting in checkout page .

**Comment by imsujan276** [comment]
can you give me more info? I do not understand what it means by "Cart Api returns Default Title but checkout api returning correct title from main product title"

**Comment by Sp2021bca** [comment]
@imsujan276  Let say i have two products one without variant second with variant.
without variants returns "Default Title" as title .
with variants return variant title.

**Comment by imsujan276** [comment]
Shopify itself returns the "Default Title" for products with no variants.

I have updated the code so that the car line merchandise has a product attribute. You can access the title from there.

**Comment by Sp2021bca** [comment]
Thanks for your quick support.
