### ISSUE TITLE
Product.dart should not contain the fields price and compareAtPrice.

### ISSUE THREAD

**Issue by WangXiaoRi** [imsujan276/shopify_flutter#79]
double get price =>
     productVariants.isEmpty ? 0 : productVariants.first.price.amount;
String get formattedPrice =>
     productVariants.isEmpty ? '' : productVariants.first.price.formattedPrice;
      
Product.dart should not contain the fields price and compareAtPrice, because this will confuse developers. These two fields belong to productVariants, so it is not appropriate to get them directly with first.

**Comment by WangXiaoRi** [comment]
Generally, the prices of different SKUs of the same product are the same, but I feel that at least a note is needed here.

**Comment by imsujan276** [comment]
The Product model contains the formattedPrice and **formattedPrice** properties to make it easy to display the price in the list where products are displayed. 

It reduces the logic of searching for the variant and getting its price. 

Yes, I do agree a note is needed for those properties. 

I will update it in later update

**Comment by WangXiaoRi** [comment]
Totally agree.
&nbsp;


飞天小麦迪
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sujan ***@***.***&gt;; 
发送时间: 2024年9月13日(星期五) 下午4:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [imsujan276/shopify_flutter] Product.dart should not contain the fields price and compareAtPrice. (Issue #79)














 
The Product model contains the formattedPrice and formattedPrice properties to make it easy to display the price in the list where products are displayed.
 
It reduces the logic of searching for the variant and getting its price.
 
Yes, I do agree a note is needed for those properties.
 
I will update it in later update
