### ISSUE TITLE
Help with phone number on user registration

### ISSUE THREAD

**Issue by FrancoTerranovaJob** [imsujan276/shopify_flutter#82]
Hi, the plugin have the phone number as nulleable on `createUserWithEmailAndPassword` method, but it seems that is required anyways, however, that is not a problem, but Im trying to use a test phone number but  I'm getting "invalid phone field" error.. I dont know how to set a correct number 

I tried for example:  +543435551111 

+54 : country code
343: country area code

**Comment by imsujan276** [comment]
The Shopify may not accept random phone numbers. Have you tried using your own number?

**Comment by imsujan276** [comment]
As for phone being required by Shopify while creating account, I have updated the package to make the phone a required field

**Comment by FrancoTerranovaJob** [comment]
Thank you for answer. Thanks for the update!
About the phone number, I dont know exactly, actually Im using this number:
+977984154321 plus one digit generated randomly and its working, and the phone that I gave you has real country code and country area
I think that If only accept real numbers it cant be tested well
