### ISSUE TITLE
Can add @inContext?

### ISSUE THREAD

**Issue by WangXiaoRi** [imsujan276/shopify_flutter#84]
Products use the @inContext directive to determine [international pricing](https://shopify.dev/docs/storefronts/headless/building-with-the-storefront-api/markets/international-pricing#create-a-cart).

**Comment by imsujan276** [comment]
The package uses [Storefront CreateCart](https://shopify.dev/docs/api/storefront/2024-07/mutations/cartCreate) and as per documentation, it does not allow using @inContext

**Comment by WangXiaoRi** [comment]
I just tried to support @incontext.
query cart($country: CountryCode, $id: ID!) @inContext(country: $country) {}. 
Query cart supports @incontext, and other list interfaces also support it. Then I can change some of them and submit them to pr.

**Comment by WangXiaoRi** [comment]
CreateCart also supports @incontext.

final data = {
      'discountCodes': cartInput.discountCodes,
      'lines': cartInput.lines.map((e) => e?.toJson()).toList(),
      'note': cartInput.note,
      'buyerIdentity': cartInput.buyerIdentity?.toJson(),
    };
    final MutationOptions createCart = MutationOptions(
      document: gql(cartCreateMutation),
      variables: {'input': data, 'country': country},
    );
    
    mutation cartCreate($country: CountryCode, $input: CartInput!) @inContext(country: $country) {}

**Comment by imsujan276** [comment]
That would be great. I will keep an eye in PR

**Comment by imsujan276** [comment]
The update is available in [v2.2.0](https://pub.dev/packages/shopify_flutter/versions/2.2.0)

**Comment by imsujan276** [comment]
#86
