### ISSUE TITLE
Field url doesn't exist on type Blog and type Article

### ISSUE THREAD

**Issue by vptcnt** [imsujan276/shopify_flutter#9]
Hello,

I got an graphql error using getAllBlogs.
In fact, url doesn't exist on type Blog and type Article
https://shopify.dev/docs/api/storefront/2023-07/objects/Article#fields
https://shopify.dev/docs/api/storefront/2023-07/objects/Blog

Maybe the field is onlineStoreUrl instead url

**Comment by imsujan276** [comment]
Yes, **url** is not **onlineStoreUrl**. 

Will update it shortly

**Comment by imsujan276** [comment]
Fixed the issue in v1.0.14

**Comment by vptcnt** [comment]
Thanks...
