### ISSUE TITLE
Sorry, I made a mistake. The currency unit of the shopping cart can only be changed by cartBuyerIdentity, not in the graphql parameter.

### ISSUE THREAD

**Issue by WangXiaoRi** [imsujan276/shopify_flutter#92]
It is invalid to use countryCode.

cartBuyerIdentityUpdate
mutation
Updates customer information associated with a cart. Buyer identity is used to determine [international pricing](https://shopify.dev/custom-storefronts/internationalization/international-pricing) and should match the customer's shipping address.

**Comment by WangXiaoRi** [comment]
When a cart is created in a country context, the resulting response is in the specified country’s currency.

**Comment by imsujan276** [comment]
Sorry, I am not getting what exactly is the issue here. 

Would you like to make it brief?

**Comment by WangXiaoRi** [comment]
I mean that countryCode can only take effect when the shopping cart interface is created in the shopping cart, and other interfaces of the shopping cart are useless, so there is no need to add internationalization.

**Comment by WangXiaoRi** [comment]
ok
