### ISSUE TITLE
CartLine.discountAllocations cannot pass the model conversion correctly.

### ISSUE THREAD

**Issue by WangXiaoRi** [imsujan276/shopify_flutter#94]
The interface returns a result, but there is no value obtained in cartLine model.

**Comment by imsujan276** [comment]
Can you add more context to it?

**Comment by WangXiaoRi** [comment]
![461727429852_ pic](https://github.com/user-attachments/assets/cd01ad5f-75d9-4f63-b378-38e3db9281c4)
![471727429874_ pic](https://github.com/user-attachments/assets/d7c8a2aa-f47e-49a9-98a1-b260cb671d9f)
![481727429912_ pic](https://github.com/user-attachments/assets/3599449f-1732-4408-9934-22361d2c3288)
You can try to apply the coupon and the discount is empty here.

**Comment by imsujan276** [comment]
why is the `discountAllocations` started with `_` as `_discountAllocations`. I think that is the cause of it

**Comment by WangXiaoRi** [comment]
thanks.

**Comment by FrancoTerranovaJob** [comment]
Same problem here, I think this is critical. Please, need fix soon @imsujan276.

**Comment by imsujan276** [comment]
This issue has been resolved in v2.2.5

**Comment by WangXiaoRi** [comment]
thanks
