### ISSUE TITLE
Create Cart Is not working with Logging User with the access Token 

### ISSUE THREAD

**Issue by harit2305** [imsujan276/shopify_flutter#96]
While creating a new cart with the help of the createCart Method of the SDK it gives type cast error from the response model 
Can anyone guide me on this 

```
      final CartInput cartInput = CartInput(
        buyerIdentity: CartBuyerIdentityInput(
          email: "test@gmail.com",
          countryCode: "IN",
          customerAccessToken: await ShopifyAuth.instance.currentCustomerAccessToken,
        ),
      );

      await _shopifyCart.createCart(cartInput).then(
        (value) {
          print("Cart data ==> ${value.toJson()}");
        },
      );
```

      Error 
      type 'String' is not a subtype of type 'num?' in type cast
      
      
      If we use the same functionality without customerAccessToken it works perfect 
      There might be some issue with the model class with the response

**Comment by imsujan276** [comment]
fixed in v2.2.6
