### ISSUE TITLE
Product should be added into the mechandise which is ProductVariant

### ISSUE THREAD

**Issue by abubakarflutter** [imsujan276/shopify_flutter#99]
![image](https://github.com/user-attachments/assets/ed0ae664-ba32-4e00-9d57-8c6b0a78bac8)

**Comment by imsujan276** [comment]
The product variant comes within the product so, adding a product inside the variant again looks like a cycle. It should ba handled from the logical end

**Comment by abubakarflutter** [comment]
But that `ProductVariant` doesn't include the actual Product Title, If we access the title it gives the variant title which is different than the Product title itself. 
BTW, I've added it in my repo. If it will require by any other person. I'll create PR
